# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.
# Project
version=1.6.1
group=net.ninjadev
java_version=25
# Common
minecraft_version=26.1.1
mod_name=FreeLook
mod_author=
mod_id=freelook
license=MIT
credits=
description=
minecraft_version_range=[26.1.1]
neo_form_version=26.1-1
# Fabric
fabric_version=0.145.4+26.1.1
fabric_loader_version=0.19.1
# Forge
forge_version=63.0.2
forge_loader_version_range=[63,)
# NeoForge
neoforge_version=26.1.1.15-beta
neoforge_loader_version_range=[4,)
# Gradle
org.gradle.java.home=C:\\Users\\jmils\\.jdks\\openjdk-25.0.1
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
